# Generated by Django 4.2.10 on 2024-02-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ChatCore", "0002_room_user_room_message"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="user_room",
            new_name="UserRoom",
        ),
    ]
