# Generated by Django 4.2.10 on 2024-02-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ChatCore", "0003_rename_user_room_userroom"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="name",
            new_name="slug",
        ),
    ]
