# Generated by Django 4.2.10 on 2024-03-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ChatCore", "0005_usersession"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="session_key",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name="UserSession",
        ),
    ]
